MACRO(RECURSE_DIRECTORY_SOURCE_FILE_GROUP)
	IF(NOT ${ARGC} EQUAL 1)

		MESSAGE(FATAL_ERROR "There is one and only one parameter")
	ENDIF()

	RECURSE_DIRECTORY_SOURCE_FILE(GROUP_FILES ${ARGV0})

	FOREACH(source ${GROUP_FILES})

		FILE(RELATIVE_PATH relative ${ARGV0} ${source})

		STRING(REGEX REPLACE "\(.*\)/.*" \\1 group ${relative})

		STRING(COMPARE EQUAL ${relative} ${group} rootGroup)

		IF (rootGroup)

			SET(group "\\")

		ELSE()

			STRING(REPLACE "/" "\\" group ${group})

		ENDIF()

		SOURCE_GROUP(${group} FILES ${source})

	ENDFOREACH()

ENDMACRO(RECURSE_DIRECTORY_SOURCE_FILE_GROUP)


MACRO(RECURSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)
	IF(NOT ${ARGC} EQUAL 0)

		MESSAGE(FATAL_ERROR "There is not need parameter")

	ENDIF()

	RECURSE_DIRECTORY_SOURCE_FILE_GROUP(${CMAKE_CURRENT_LIST_DIR})

ENDMACRO(RECURSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)

MACRO(TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 1)

		MESSAGE(FATAL_ERROR "There is one and only one parameter")

	ENDIF()

	TRAVERSE_DIRECTORY_SOURCE_FILE(GROUP_FILES ${ARGV0})

	FOREACH(source ${GROUP_FILES})

		FILE(RELATIVE_PATH relative ${ARGV0} ${source})

		STRING(REGEX REPLACE "\(.*\)/.*" \\1 group ${relative})

		STRING(COMPARE EQUAL ${relative} ${group} rootGroup)

		IF (rootGroup)

			SET(group "\\")

		ELSE()

			STRING(REPLACE "/" "\\" group ${group})

		ENDIF()

		SOURCE_GROUP(${group} FILES ${source})

	ENDFOREACH()

ENDMACRO(TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP)


MACRO(TRAVERSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 0)

		MESSAGE(FATAL_ERROR "There is not need parameter")

	ENDIF()

	TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP(${CMAKE_CURRENT_LIST_DIR})

ENDMACRO(TRAVERSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)
