SET(CMAKE_DISABLE_SOURCE_CHANGES ON)
SET(CMAKE_DISABLE_IN_SOURCE_BUILD ON)

SET(CMAKE_SKIP_BUILD_RPATH FALSE)
SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
SET(CMAKE_INSTALL_RPATH ${LIBRARY_INSTALL_PREFIX})
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

SET_PROPERTY(GLOBAL PROPERTY USE_FOLDERS ON)
