MACRO(TRAVERSE_INCLUDE_DIRECTORIES)
	IF(${ARGC} LESS 1)

		MESSAGE(FATAL_ERROR "Has and is greater than one parameter")

	ENDIF()

	FOREACH(param ${ARGN})

		INCLUDE_DIRECTORIES(${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE_DIRECTORIES)

MACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)
	IF(${ARGC} LESS 1)

		MESSAGE(FATAL_ERROR "Has and is greater than one parameter")

	ENDIF()

	FOREACH(param ${ARGN})

		TARGET_INCLUDE_DIRECTORIES(${PROGRAM_NAME}	PUBLIC	${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)
