MACRO(TRAVERSE_INSTALL_INCLUDE)
	IF(NOT ${ARGC} EQUAL 2)

		MESSAGE(FATAL_ERROR "There is two and only two parameter")

	ENDIF()

	FILE(GLOB INSTALL_FILES		"${ARGV0}/*.h"
								"${ARGV0}/*.hh"
								"${ARGV0}/*.hpp")

	INSTALL(PROGRAMS ${INSTALL_FILES} DESTINATION ${ARGV1})

ENDMACRO(TRAVERSE_INSTALL_INCLUDE)
